[theme]
primaryColor = "#00CC96"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = false
address = "0.0.0.0"
port = 55468

[browser]
gatherUsageStats = false